"""memory_facts CRUD + the MEMORY.md digest renderer.

The digest is the always-in-context half of recall: the top high-confidence lessons (by
staleness-decayed ``c_eff``) plus operator corrections, written between sentinel markers
into Hermes's ``~/.hermes/memories/MEMORY.md`` so they are injected at session start and
survive context compression. The write is atomic and confined to the marker block, so it
is drift-guard-safe and never clobbers operator-authored memory above/below.
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Any, Optional

from . import vectors
from .learning import c_eff
from .util import jaccard, now_iso, tokenize

BEGIN = "<!-- KQ:DIGEST:BEGIN -->"
END = "<!-- KQ:DIGEST:END -->"


def remember(
    store: Any,
    content: str,
    scope: str = "kq",
    kind: Optional[str] = None,
    source: Optional[str] = None,
) -> dict:
    """Store a declarative fact, de-duplicated against existing facts in the same scope."""
    qunit = store.embed_query_unit(content) if store.semantic else None
    rows = store.query(
        "SELECT id, embedding_id, content FROM memory_facts WHERE status='active' AND scope=?",
        (scope,),
    )
    dup_id = None
    if qunit is not None and rows:
        ids = [int(r["id"]) for r in rows]
        vecs = [store.get_unit_vector(r["embedding_id"]) for r in rows]
        sim, idx = vectors.max_cosine(qunit, vecs)
        if idx >= 0 and sim >= store.cfg.dedup_fact:
            dup_id = ids[idx]
    elif rows:
        qt = tokenize(content)
        best, best_id = 0.0, -1
        for r in rows:
            s = jaccard(qt, tokenize(r["content"]))
            if s > best:
                best, best_id = s, int(r["id"])
        if best_id >= 0 and best >= store.cfg.dedup_fact:
            dup_id = best_id

    ts = now_iso()
    if dup_id is not None:
        store.execute("UPDATE memory_facts SET updated_at=? WHERE id=?", (ts, dup_id))
        return {"ok": True, "fact_id": dup_id, "action": "duplicate"}

    emb_id = store.put_embedding(content) if store.semantic else None
    with store.lock:
        cur = store.conn.execute(
            "INSERT INTO memory_facts(content, scope, kind, source, embedding_id, created_at, updated_at) "
            "VALUES (?,?,?,?,?,?,?)",
            (content, scope, kind, source, emb_id, ts, ts),
        )
        store.conn.commit()
        fid = int(cur.lastrowid)
    return {"ok": True, "fact_id": fid, "action": "inserted"}


def render_digest(store: Any) -> str:
    """Build the inner digest text (no markers)."""
    cfg = store.cfg
    now = now_iso()
    lessons = store.query("SELECT * FROM lessons WHERE status='active'")
    ranked = sorted(
        ((c_eff(store, float(r["confidence"]), r["last_used_at"] or r["updated_at"], now), r) for r in lessons),
        key=lambda kv: kv[0],
        reverse=True,
    )
    corrections = store.query(
        "SELECT content FROM memory_facts WHERE status='active' AND scope='operator' AND kind='correction' "
        "ORDER BY updated_at DESC LIMIT 20"
    )

    lines: list[str] = ["## Killer Queen — Learned Memory",
                        "_Auto-generated by KQ Core. Do not edit between the markers._", ""]
    if corrections:
        lines.append("### Operator corrections (highest priority)")
        for r in corrections:
            lines.append(f"- {r['content'].strip()}")
        lines.append("")

    lines.append(f"### Top lessons ({min(len(ranked), cfg.digest_top_n)} of {len(ranked)} active)")
    budget = cfg.digest_budget_chars
    used = sum(len(x) + 1 for x in lines)
    shown = 0
    for _score, r in ranked:
        if shown >= cfg.digest_top_n:
            break
        seg = f"- [{r['band']}] {r['summary'].strip()}"
        tw, ad = (r["trigger_when"] or "").strip(), (r["action_do"] or "").strip()
        if tw or ad:
            seg += f" — IF {tw or 'applicable'} THEN {ad or 'apply'}"
        if used + len(seg) + 1 > budget:
            break
        lines.append(seg)
        used += len(seg) + 1
        shown += 1
    if not ranked:
        lines.append("- (no lessons recorded yet)")
    return "\n".join(lines).rstrip() + "\n"


def _splice(existing: str, inner: str) -> str:
    block = f"{BEGIN}\n{inner.rstrip()}\n{END}"
    if BEGIN in existing and END in existing:
        pre = existing.split(BEGIN, 1)[0].rstrip()
        post = existing.split(END, 1)[1].lstrip()
        parts = [p for p in (pre, block, post) if p]
        return "\n\n".join(parts).rstrip() + "\n"
    if existing.strip():
        return existing.rstrip() + "\n\n" + block + "\n"
    return block + "\n"


def write_digest(store: Any, path: Optional[Path | str] = None) -> dict:
    """Render + atomically splice the digest into the MEMORY.md marker block."""
    target = Path(path) if path is not None else store.cfg.memory_md
    target.parent.mkdir(parents=True, exist_ok=True)
    inner = render_digest(store)
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    new_text = _splice(existing, inner)
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".kqtmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_text)
        os.replace(tmp, target)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
    n = store.query_one("SELECT COUNT(*) AS c FROM lessons WHERE status='active'")
    return {"ok": True, "path": str(target), "active_lessons": int(n["c"]) if n else 0,
            "bytes": len(new_text.encode("utf-8"))}
